name = "RebranchingIP"
uuid = "1606fce2-2368-42bf-91f9-4d3e6ac730d4"
authors = ["nzy1997"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
